import * as React from "react"
import { StaticImage } from "gatsby-plugin-image"

const Photogrid = () => {
  return (
    <section className="black-white fullgrid">
      <div className="photogridrow">
        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/1.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/2.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/3.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/4.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/5.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/6.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/7.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/8.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/9.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/10.jpg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">

          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/11.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/12.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/13.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/14.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/15.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/16.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/17.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/18.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/19.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/20.jpg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">

          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/21.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/22.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/23.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/24.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/25.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/26.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/27.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/28.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/29.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/30.jpg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/31.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/32.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/33.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/34.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/35.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/36.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/37.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/38.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/39.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/40.jpg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>

        <div className="photogridcol">
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/41.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/42.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/43.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/44.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/45.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/46.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/47.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/48.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/49.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/50.jpg"
            alt="me"
            placeholder="dominantColor"
          />
          <StaticImage
            className="gridphoto"
            src="../../images/fullgrid/51.jpg"
            alt="me"
            placeholder="dominantColor"
          />
        </div>
      </div>

    </section>
  )
}
export default Photogrid
